// ==UserScript==
// @name         GBF Co-op English Autotranslate
// @namespace    https://codensity.github.io/
// @version      20190108.1
// @description  Translates room descriptions into English
// @match        *://game.granbluefantasy.jp/*
// @match        *://gbf.game.mbga.jp/*
// @license      MIT
// ==/UserScript==

(function() {
    "use strict";

    // Based on /u/finis_caelorum's Co-op Lobby Phrasebook:
    // https://www.reddit.com/r/Granblue_en/comments/6nucg3/coop_lobby_phrasebook/
    // Authors: /u/codensite /u/Seileach
    let translations = [

        ["グラブル", "GBF"],

        // Some early phrases to catch some stuffs
        ["　", " "],
        ["ハード", "Hard"],
        ["ノーマル", "Normal"],
        ["通常", "Normal"],
        ["信念", "Creeds"],
        ["集め", " collecting"],
        ["あつめ", " collecting"],
        ["集", " collecting"],
        ["オセロ", "Othello"], // Are you playing the right game here?
        ["本戦", "Finals"],
        ["古戦場", "GuildWar"],
        ["古戦", "GuildWar"],
        ["クエスト", "Quest"],
        ["やる気のある", "Motivated"],
        ["名言集", "PopularQuotes"],
        ["名言", "PopularQuotes"],

        ["デイリー", "Daily"],
        ["でいりー", "Daily"],
        ["日課", "Daily"],
        ["毎日", "Daily"],
        ["ランク", "Rank"],
        ["ランク帯", "Rank"],

        ["要職", "Need"],
        ["必要", "Required"],
        ["要", "Require"],
        ["火力", "Carry"],
        ["強者", "Carry"],
        ["ワンパン禁止", "No Wanpan"],
        ["ワンパン", "Wanpan"],
        ["人から開始", "players before starting"],
        ["人から", "players before starting"],
        ["数人から", "Many players before starting"],
        ["経験者", "Experienced"],
        ["經驗者", "Experienced"],
        ["行動理解者", "Experienced"],
        ["理解者", "Experienced"],
        ["慣れた方", "Experienced"],
        ["強い人", "StrongPlayer"],
        ["不慣れ", "Inexperienced"],
        ["不慣", "Inexperienced"],
        ["慣れてません", "Inexperienced"],
        ["初心者", "Newbie"],
        ["初心", "Newbie"],
        ["開始", "Start"],
        ["スタート", "Start"],
        ["出発", "Start"],
        ["程", "Start"],
        ["キック", "Kick"],
        ["蹴り", "Kick"],
        ["承認", "Confirm"],
        ["認証", "Confirm"],
        ["オート", "Auto"],
        ["最後", "Last"],
        ["枠", "Spot"],

        ["裁考", "VohuManah"],
        ["ゼノウォフマナフ", "XenoVohuManah"],
        ["ゼノウォフ", "XenoVohuManah"],
        ["ウォフマナフ", "VohuManah"],
        ["ウォフ", "VohuManah"],
        ["灼滅", "Ifrit"],
        ["ゼノイフリート", "XenoIfrit"],
        ["ゼノイフ", "XenoIfrit"],
        ["イフリート", "Ifrit"],
        ["イフ", "Ifrit"],
        ["ゼノコロウ", "XenoCorow"],
        ["ゼノコロゥ", "XenoCorow"],
        ["ゼノコロ", "XenoCorow"],
        ["妃光", "Corow"],
        ["コロウ", "Corow"],
        ["コロゥ", "Corow"],
        ["氷獄", "Cocytus"],
        ["ゼノコキュートス", "XenoCocytus"],
        ["ゼノコキュ", "XenoCocytus"],
        ["コキュートス", "Cocytus"],
        ["コキュ", "Cocy"],
        ["人馬", "Sagi"],
        ["ゼノサジタリウス", "XenoSagittarius"],
        ["ゼノサジ", "XenoSagi"],
        ["サジタリウス", "Sagittarius"],
        ["サジ", "Sagi"],
        ["幻魔", "Diablo"],
        ["ゼノディアボロス", "XenoDiablo"],
        ["ゼノディア", "XenoDiablo"],
        ["ディアボロス", "Diablo"],
        ["ディア", "Diablo"],
        ["アスタロト", "Astaroth"],

        ["ティアマト", "Tiamat"],
        ["ティア", "Tia"],
        ["エア", "Ayr"],
        ["コロッサス", "Colossus"],
        ["コロ", "Colo"],
        ["リヴァイアサン", "Leviathan"],
        ["リバァイアサン", "Leviathan"],
        ["鰻", "Levi"],
        ["うなぎ", "Levi"],
        ["リヴァ", "Levi"],
        ["ユグドラシル", "Yggdrasil"],
        ["ゆぐゆぐ", "Yuguyugu"],
        ["ゆぐ", "Yugu"],
        ["ユグ", "Yugu"],
        ["シュヴァリエ", "Luminiera"],
        ["シュバリエ", "Luminiera"],
        ["シュヴァ", "Lumi"],
        ["シュヴ", "Lumi"],
        ["シュバ", "Lumi"],
        ["セレスト", "Celeste"],
        ["セレ", "Celeste"],
        ["ボート", "Celeste"],
        ["船", "Celeste"],
        ["マグナ", "Magna"],
        ["マグ", "Magna"],
        ["まぐな", "Magna"],
        ["まぐ", "Magna"],

        ["邂逅、黒銀の翼", "Proto-Baha"],
        ["邂逅黑", "Proto-Baha"],
        ["邂逅", "Proto-Baha"],
        ["ヨワ", "Proto-"],
        ["プロト", "Proto-"],

        ["黒銀の翼", "Proto-BahaHL"],
        ["弱ばはむと", "Proto-BahaHL"],
        ["弱バハムート", "Baha"],
        ["弱バハムト", "Proto-BahaHL"],
        ["弱バハ", "Proto-BahaHL"],
        ["弱ババ", "Proto-BahaHL"],
        ["弱ﾊﾞﾊ", "Proto-BahaHL"],
        ["弱ばは", "Proto-BahaHL"],
        ["弱八八", "Proto-BahaHL"],
        ["よわばはむと", "Proto-BahaHL"],
        ["よわバハムート", "Baha"],
        ["よわバハムト", "Proto-BahaHL"],
        ["よわバハ", "Proto-BahaHL"],
        ["よわババ", "Proto-BahaHL"],
        ["よわﾊﾞﾊ", "Proto-BahaHL"],
        ["よわばは", "Proto-BahaHL"],
        ["つよいばはむと", "Proto-BahaHL"],
        ["つよいバハムート", "Baha"],
        ["つよいバハムト", "Proto-BahaHL"],
        ["つよいバハ", "Proto-BahaHL"],
        ["つよいババ", "Proto-BahaHL"],
        ["つよいﾊﾞﾊ", "Proto-BahaHL"],
        ["つよいばは", "Proto-BahaHL"],
        ["つよい", "Proto-BahaHL"],
        ["つょいばはむと", "Proto-BahaHL"],
        ["つょいバハムート", "Baha"],
        ["つょいバハムト", "Proto-BahaHL"],
        ["つょいバハ", "Proto-BahaHL"],
        ["つょいババ", "Proto-BahaHL"],
        ["つょいﾊﾞﾊ", "Proto-BahaHL"],
        ["つょいばは", "Proto-BahaHL"],
        ["つょい", "Proto-BahaHL"],
        ["つよばはむと", "Proto-BahaHL"],
        ["つよバハムート", "Baha"],
        ["つよバハムト", "Proto-BahaHL"],
        ["つよバハ", "Proto-BahaHL"],
        ["つよババ", "Proto-BahaHL"],
        ["つよﾊﾞﾊ", "Proto-BahaHL"],
        ["つよばは", "Proto-BahaHL"],
        ["つよ", "Proto-BahaHL"],
        ["つょばはむと", "Proto-BahaHL"],
        ["つょバハムート", "Baha"],
        ["つょバハムト", "Proto-BahaHL"],
        ["つょバハ", "Proto-BahaHL"],
        ["つょババ", "Proto-BahaHL"],
        ["つょﾊﾞﾊ", "Proto-BahaHL"],
        ["つょばは", "Proto-BahaHL"],
        ["ツヨイばはむと", "Proto-BahaHL"],
        ["ツヨイバハムート", "Baha"],
        ["ツヨイバハムト", "Proto-BahaHL"],
        ["ツヨイバハ", "Proto-BahaHL"],
        ["ツヨイババ", "Proto-BahaHL"],
        ["ツヨイﾊﾞﾊ", "Proto-BahaHL"],
        ["ツヨイばは", "Proto-BahaHL"],
        ["ツヨばはむと", "Proto-BahaHL"],
        ["ツヨバハムート", "Baha"],
        ["ツヨバハムト", "Proto-BahaHL"],
        ["ツヨバハ", "Proto-BahaHL"],
        ["ツヨババ", "Proto-BahaHL"],
        ["ツヨﾊﾞﾊ", "Proto-BahaHL"],
        ["ツヨばは", "Proto-BahaHL"],
        ["ﾂﾖｲﾊﾞﾊ", "Proto-BahaHL"],
        ["ﾂﾖﾊﾞﾊ", "Proto-BahaHL"],
        ["強いバハ", "Proto-BahaHL"],
        ["強バハ", "Proto-BahaHL"],
        ["強ﾊﾞﾊ", "Proto-BahaHL"],
        ["強八八", "Proto-BahaHL"],
        ["強ばは", "Proto-BahaHL"],
        ["ツヨばはむと", "Proto-BahaHL"],
        ["ツヨバハムート", "Baha"],
        ["ツヨバハムト", "Proto-BahaHL"],
        ["ツヨバハ", "Proto-BahaHL"],
        ["ツヨババ", "Proto-BahaHL"],
        ["ツヨﾊﾞﾊ", "Proto-BahaHL"],
        ["ツヨばは", "Proto-BahaHL"],

        ["アルばはむと", "Ult-Baha"],
        ["アルバハムート", "Baha"],
        ["アルバハムト", "Ult-Baha"],
        ["アルバハ", "Ult-Baha"],
        ["アルババ", "Ult-Baha"],
        ["アルばは", "Ult-Baha"],
        ["ア ル バ ハ", "Ult-Baha"],
        ["ｱﾙﾊﾞﾊ", "Ult-Baha"],
        ["アばはむと", "Ult-Baha"],
        ["アバハムート", "Baha"],
        ["アバハムト", "Ult-Baha"],
        ["アバハ", "Ult-Baha"],
        ["アババ", "Ult-Baha"],
        ["アばは", "Ult-Baha"],
        ["ｱﾊﾞﾊ", "Ult-Baha"],
        ["あるばはむと", "Ult-Baha"],
        ["あるバハムート", "Baha"],
        ["あるバハムト", "Ult-Baha"],
        ["あるバハ", "Ult-Baha"],
        ["あるババ", "Ult-Baha"],
        ["あるばは", "Ult-Baha"],
        ["おはバハ", "Ult-Baha"],
        ["了儿八八", "Ult-Baha"],
        ["アルティメットバハムート", "Ult-Baha"],
        ["アルティメット", "Ult-"],
        ["アルティメ", "Ult-Baha"],
        ["ばはむと", "Baha"],
        ["バハムート", "Baha"],
        ["バハムト", "Baha"],
        ["バハ", "Baha"],
        ["ババ", "Baha"],
        ["ﾊﾞﾊ", "Baha"],
        ["ばは", "Baha"],
        ["八八", "Baha"],

        ["最終ソーン", "5★Song"],
        ["最終", "5★"],
        ["解放", "Uncapped"],
        ["ソーン", "Song"],
        ["シャオ", "Shao"],
        ["ｼｬｵ", "Shao"],
        ["麻痺延長有り", "ParaExtend"],
        ["麻痺延長有", "ParaExtend"],
        ["麻痺延長", "ParaExtend"],
        ["麻痺", "Para"],
        ["麻痹", "Para"],
        ["麻", "Para"],
        ["痹", "Para"],
        ["痺", "Para"],
        ["マヒ", "Para"],
        ["延長", "Extend"],
        ["延", "Extend"],
        ["デバフ", "Debuff"],
        ["ブレーキ", "Break"],
        ["ブレキ", "Break"],
        ["ﾌﾞﾚｷ", "Break"],
        ["ブレ", "Break"],
        ["ﾌﾞﾚ", "Break"],
        ["ぶれ", "Break"],
        ["恐怖", "Fear"],
        ["魅了", "Charm"],
        ["誘惑", "Entice"],
        ["ミスト", "Mist"],
        ["ウニア", "Unia"],
        ["ブリザード", "Blizzard"],
        ["ブリザ", "Blizzard"],
        ["ブリ", "Blizzard"],
        ["フリー", "Blizzard"],
        ["ﾌﾞﾘ", "Blizzard"],
        ["鰤", "Blizzard"],
        ["ぶり", "Blizzard"],
        ["ﾌﾞﾘｻﾞｰﾄﾞ", "Blizzard"],
        ["ﾌﾞﾘｻﾞ", "Blizzard"],
        ["ﾌﾞﾘｰ", "Blizzard"],
        ["ﾌﾞﾘ", "Blizzard"],
        ["フレア", "Flare"],
        ["フレ", "Flare"],
        ["ﾌﾚｱ", "Flare"],
        ["ﾌﾚ", "Flare"],
        ["ふれ", "Flare"],
        ["原子崩壊", "Atomic"],
        ["崩壊", "Atomic"],
        ["領域", " Fields"],
        ["喪失", "Forfeit"],
        ["喪", "Forfeit"],
        ["カトル", "Forfeit"],
        ["回復", "Heal"],
        ["アビダメ", "Ability Damage"],
        ["アビ", "Ability"],
        ["スキル", "Skill"],
        ["ソウルピルファー", "Soul Soloist"],
        ["ピルファー", "Soul Soloist"],
        ["グラビ", "Gravity"],
        ["トレハン", "TreasureHunt"],
        ["トール持ち", "ThorOwner"],
        ["トル持ち", "ThorOwner"],
        ["ト持ち", "ThorOwner"],
        ["卜持ち", "ThorOwner"],
        ["ﾄ持ち", "ThorOwner"],
        ["ト持", "ThorOwner"],
        ["卜持", "ThorOwner"],
        ["ﾄ持", "ThorOwner"],
        ["トール", "Thor"],
        ["トル", "Thor"],
        ["ﾄｰﾙ", "Thor"],
        ["ﾄﾙ", "Thor"],
        ["托", "Thor"],
        ["石持ち", "HaveSummon"],
        ["石持者", "SummonOwner"],
        ["石持", "HaveSummon"],
        ["石無し", "NoSummon"],
        ["石無", "NoSummon"],
        ["無石", "NoSummon"],
        ["石なし", "NoSummon"],
        ["持ち", "Owner"],
        ["持", "Owner"],
        ["鰹", "Bonito"],
        ["基", "0★"],
        ["未凸", "0★"],
        ["4凸", "4★"],
        ["担当", "Responsible"],
        ["さくっと", "Speedrun"],
        ["高速", "Speedrun"],
        ["速度", "Speedrun"],
        ["ぶん流し", "Speedrun"],
        ["飛ばし", "Speedrun"],
        ["スピード", "Speedrun"],
        ["速", "Fast"],
        ["サポ", "Support"],
        ["編成", "Team"],
        ["攻撃", "Attack"],

        ["スラ爆", "Slimeblasting"],
        ["順貼り", "Train (Host in join order)"],
        ["順張り", "Train (Host in join order)"],
        ["逆順貼り", "Train (Host in reverse join order)"],
        ["逆順張り", "Train (Host in reverse join order)"],
        ["時間貼り", "(Split hosting by time)"],
        ["主全貼り", "(Host is hosting)"],
        ["主連貼り", "(Host is hosting)"],
        ["主貼り", "(Host is hosting)"],
        ["主貼", "(Host is hosting)"],
        ["主張り", "(Host is hosting)"],
        ["自発", "Hosting"],
        ["自發", "Hosting"],
        ["交代", "(Take turns hosting)"],
        ["分交代", " minute hosting shifts"],
        ["分", " minutes"],
        ["汁飲みます", "(will elixir)"],
        ["ＨＬ", "HL"],
        ["ｈｌ", "HL"],
        ["hl", "HL"],
        ["ステージ", "Stage"],
        ["以上", "Above"],
        ["上", "Above"],
        ["まで", "AtLeast"],
        ["以下", "Below"],
        ["周回", "Grind"],
        ["繰り返す", "Repeats"],
        ["連続", "Repeats"],
        ["連續", "Repeats"],
        ["連覇", "Repeats"],
        ["連戦", "RerunBattles"], // not always a train?
        ["何周か", "Multiple Times"],
        ["一戦", "Once"],
        ["一回", "Once"],
        ["いっかい", "Once"],
        ["単発", "Once"],
        ["一度", "Once"],
        ["戦", "Battle"],
        ["連", "times"],
        ["连", "times"],
        ["回", "times"],
        ["次", "times"],
        ["回やります", "Times"],
        ["全", "All"],
        ["人", "players"],
        ["クリア", "Clear"],
        ["討伐", "Subjugate"],
        ["目的", "Objective"],
        ["目標", "Objective"],
        ["詳細", "Detail"],
        ["内部", "Inside"],
        ["未定", "Undetermined"],
        ["進めたいです", "Progression"],
        ["進行", "Progression"],
        ["階層", "Tier"],

        // Drops

        ["ドロップ", "Drop"],
        ["落ちる", "Drop"],
        ["落ち", "Drop"],
        ["落", "Drop"],
        ["クリスタル", "Crystal"],
        ["稼ぎ", "Farm"],
        ["木箱", "WoodenChest"],
        ["銀箱", "SilverChest"],
        ["銀", "SilverChest"],
        ["赤箱", "RedChest"],
        ["青箱", "BlueChest"],
        ["碧空の結晶", "BlueSkyCrystal"],
        ["碧空結晶", "BlueSkyCrystal"],
        ["碧空", "BlueSkyCrystal"],
        ["結晶", "Crystal"],
        ["銀天の輝", "SilverCentrum"],
        ["銀天", "SilverCentrum"],
        ["輝き", "SilverCentrum"],
        ["輝", "Centrum"],
        ["アニマ", "Anima"],
        ["アニ", "Anima"],
        ["プシュケー", "Anima"],
        ["プシュ", "Anima"],
        ["アヴェンジャー", "Avenger"],
        ["スコフニュング", "Skofnung"],
        ["ニルヴァーナ", "Nirvana"],
        ["ケラウノス", "Keraunos"],
        ["オリバー", "Oliver"],
        ["イペタム", "Ipetam"],
        ["鬼神の籠手", "Hellion Gauntlet"],
        ["ローゼンボーゲン", "Rosenbogen"],
        ["ランゲレイク", "Langelik"],
        ["ロムルスの槍", "Romulus Spear"],
        ["ファウスト", "Faust"],
        ["天叢雲剣", "Murakamo"],
        ["千子村正", "Muramasa"],
        ["アシュケロン", "Aschallon"],
        ["ネブカドネザル", "Nebuchad"],
        ["カピラヴァストゥ", "Kapilavastu"],
        ["ミセリコルデ", "Misericorde"],
        ["レプリカ", "Replica"],
        ["剣闘士の証", "Gladiator Distinction"],
        ["守護騎士の証", "Guardian Distinction"],
        ["聖職者の証", "Pilgrim Distinction"],
        ["魔導士の証", "Mage Distinction"],
        ["盗賊の証", "Bandit Distinction"],
        ["魔剣士の証", "Fencer Distinction"],
        ["格闘士の証", "Combatant Distinction"],
        ["射手の証", "Sharpshooter Distinction"],
        ["吟遊詩人の証", "Troubadour Distinction"],
        ["槍騎兵の証", "Cavalryman Distinction"],
        ["錬金術師の証", "Alchemist Distinction"],
        ["侍の証", "Samurai Distinction"],
        ["忍の証", "Ninja Distinction"],
        ["剣聖の証", "Sword Master Distinction"],
        ["撃手の証", "Gunslinger Distinction"],
        ["賢者の証", "Mystic Distinction"],
        ["暗殺者の証", "Assassin Distinction"],
        ["戦士の信念", "Warrior Creed"],
        ["魔導士の信念", "Mage Creed"],
        ["証", "Distinction"],
        ["栄光の証", "ChampionMerit"],
        ["栄光", "Champion"],
        ["覇者の証", "SupremeMerit"],
        ["覇者", "Supreme"],
        ["究竟の証", "LegendaryMerit"],
        ["究竟", "Supreme"],
        ["証", "Merit"],
        ["朽", "Rusted"],
        ["武器", "Weapon"],
        ["騎士の誇り", "KnightEsteem"],
	    ["騎士誇り", "KnightEsteem"],
	    ["賢者の誇り", "SageEsteem"],
	    ["賢者誇り", "SageEsteem"],
        ["紫電角", "PrimevalHorn"],
        ["角", "Horn"],
        ["ヒヒイロカネ", "GoldBrick"],
        ["ヒヒイロ", "GoldBrick"],
        ["強化", "Improve"],
        ["拳", "Fist"],
        ["おっけ", "AES"],
        ["重視", "Focus"],

        ["環境", "Debuffs"],
        ["くらいから", "About"], // Starts around this many players
        ["ぐらいから", "About"], // Same as above
        ["ぐらいで", "About"], // Same as above
        ["前後", "About"], // Same as above
        ["から", "About"],
        ["適当", "Appropriate"],
        ["フル", "Full"],
        ["クラス", "Tier"], //GW

        ["主弱", "Newbie"],
        ["主雑魚", "Newbie"],
        ["主", "Host Is "],
        ["弱い", "Newbie"],
        ["弱", "Newbie"],
        ["雑魚", "Newbie"],
        ["しょしんしゃ", "Newbie"],
        ["募集", " Needed"],
        ["募", " Needed"],
        ["求", " Needed"],
        ["開幕", "AtStart"],
        ["開", "AtStart"],
        ["初手", "AtStart"],
        ["救援", "Backup"],
        ["救助", "Backup"],
        ["放置", "AFK"],
        ["摸魚", "AFK"],
        ["有り", "Available"],
        ["有", "Available"],
        ["あり", "Available"],
        ["ある", "Available"],
        ["無い", "Available"],
        ["無し", "Not Available"],
        ["無", "Not Available"],
        ["なし", "Not Available"],
        ["禁止", "Prohibited"],
        ["禁", "Prohibited"],
        ["厳禁", "Prohibited"],
        ["ダメ", "Prohibited"],
        ["最初", "First"],
        ["初めて", "FirstTime"],
        ["初見", "FirstTime"],
        ["初", "First"],
        ["挑戦", "Challenge"],

        ["ファイター", "Fighter"],
        ["ナイト", "Knight"],
        ["プリースト", "Priest"],
        ["ウィザード", "Wizard"],
        ["シーフ", "Thief"],
        ["エンハンサー", "Enhancer"],
        ["グラップラー", "Grappler"],
        ["レンジャー", "Ranger"],
        ["ハーピスト", "Harpist"],
        ["ランサー", "Lancer"],
        ["ウォーリア", "Warrior"],
        ["フォートレス", "Sentinel"],
        ["クレリック", "Cleric"],
        ["ソーサラー", "Sorcerer"],
        ["レイダー", "Raider"],
        ["アルカナソード", "Arcana Dueler"],
        ["クンフー", "Kung Fu Artist"],
        ["マークスマン", "Archer"],
        ["ミンストレル", "Bard"],
        ["ドラグーン", "Dragoon"],
        ["ホーリーセイバー", "Holy Saber"],
        ["ホリセ", "Holy Saber"],
        ["ビショップ", "Bishop"],
        ["ハーミット", "Hermit"],
        ["ホークアイ", "Hawkeye"],
        ["オーガ", "Ogre"],
        ["サイドワインダー", "Sidewinder"],
        ["ヴァルキュリア", "Valkyrie"],
        ["ベルセルク", "Berserker"],
        ["ウォーロック", "Warlock"],
        ["ギゾク", "Bandit Tycoon"],
        ["ぎぞく", "Bandit Tycoon"],
        ["GZ", "Bandit Tycoon"],
        ["カオスルーダー", "Chaos Ruler"],
        ["ハウンドドッグ", "Nighthound"],
        ["エリュシオン", "Elysian"],
        ["アルケミスト", "Alchemist"],
        ["忍者", "Ninja"],
        ["侍", "Samurai"],
        ["剣聖", "Sword Master"],
        ["ガンスリンガー", "Gunslinger"],
        ["賢者", "Mystic"],
        ["アサシン", "Assassin"],
        ["ドラムマスター", "Drum Master"],
        ["ダンサー", "Dancer"],
        ["メカニック", "Mechanic"],
        ["ポンマス", "Weapon Master"],
        ["パスタ", "Superstar"],
        ["がおー", "Berserker"],
        ["ガオー", "Berserker"],
        ["ベルセ", "Berserker"],
        ["ウォロ", "Warlock"],
        ["魚", "Warlock"],
        ["ダクフェ", "Dark Fencer"],
        ["カオル", "Chaos Ruler"],
        ["ドラマス", "Drum Master"],
        ["エリュ", "Elysian"],
        ["エリ", "Elysian"],
        ["ｴﾘｭ", "Elysian"],
        ["スパルタン", "Spartan"],
        ["スパルタ", "Spartan"],
        ["スパト", "Spartan"],
        ["スパ", "Spartan"],
        ["義賊", "Bandit Tycoon"],
        ["ハウンド", "Nighthound"],
        ["アプサラス", "Apsaras"],
        ["レスラー", "Luchador"],
        ["セージ", "Sage"],
        ["セジ", "Sage"],
        ["セ", "Sage"],
        ["ｾｰｼﾞ", "Sage"],
        ["ｾ", "Sage"],
        ["せ", "Sage"],
        ["スセ", "Spart/Sage"],
        ["セエ", "Sage/Elysian"],
        ["ザ・グローリー", "Glorybringer"],
        ["グローリー", "Glorybringer"],
        ["剣聖", "Glorybringer"],
        ["黒猫道士", "Nekomancer"],
        ["黒猫", "Nekomancer"],
        ["猫", "Nekomancer"],
        ["道士", "Nekomancer"],
        ["剣豪", "Kengo"],
        ["魔法戦士", "Runeslayer"],
        ["ドクター", "Doctor"],
        ["ダンサー", "Dancer"],
        ["のみ", "Only"],
        ["だけ", "Only"],
        ["どなたでも", "Anyone"],
        ["誰でも", "Anyone"],
        ["ご自由に", "FreeForAllRace"],
        ["Mフリー", "FreeForAllRace"],

        ["剣", "Sword"],
        ["劍", "Sword"],
        ["杖", "Staff"],
        ["弓", "Bow"],

        ["ゼノ", "Xeno"],

        ["波濤", "Neptune"],
        ["ネプネプ", "Neptune"],
        ["ネプチューン", "Neptune"],
        ["ネプ", "Neptune"],
        ["花信風", "Zephyrus"],
        ["ゼピュロス", "Zephyrus"],
        ["ゼピュ", "Zephyrus"],
        ["巨巌", "Titan"],
        ["ティターン", "Titan"],
        ["ティタ", "Titan"],
        ["マッチョ", "Titan"], // macho
        ["揺炎", "Agni"],
        ["アグニス", "Agni"],

        ["ローズクイーン", "RoseQueen"],
        ["ローズタ", "RoseQueen"],
        ["ローズ", "RoseQueen"],
        ["ﾛｰｽﾞｸｲｰﾝ", "RoseQueen"],
        ["ﾛｰｽﾞ", "RoseQueen"],
        ["薔薇", "RoseQueen"],
        ["ろーず", "RoseQueen"],
        ["ロゼッタ", "RoseQueen"],
        ["調停の翼", "Grande"],
        ["ジ・オーダー・グランデ", "Grande"],
        ["ジ・オーダー・グランテ", "Grande"],
        ["ジオグラ", "Grande"],
        ["グランデ", "Grande"],
        ["グランテ", "Grande"],
        ["ンデ", "Grande"],
        ["ンテ", "Grande"],
        ["ぐらんで", "Grande"],
        ["んで", "Grande"],
        ["調停", "Grande"],
        ["ゾーイ", "Grande"],
        ["ぞーい", "Grande"],

        ["旧石", "T1"],
        ["ナタク", "Nezha"],
        ["ナタ", "Nezha"],
        ["マキュウラマリウス", "MaculaMarius"],
        ["マキュラマリウス", "MaculaMarius"],
        ["マキュウラ", "MaculaMarius"],
        ["マキュラ", "Macula"],
        ["マキュ", "Macula"],
        ["マリウス", "Marius"],
        ["メドゥーサ", "Medusa"],
        ["メドｳーサ", "Medusa"],
        ["メドューサ", "Medusa"],
        ["メデューサ", "Medusa"],
        ["メデゥーサ", "Medusa"],
        ["メドゥ子", "Medusa"],
        ["メデュ子", "Medusa"],
        ["メデゥ子", "Medusa"],
        ["メデュ", "Medusa"],
        ["メデゥ", "Medusa"],
        ["メドコ", "Medusa"],
        ["メドゥ", "Medusa"],
        ["メド", "Medusa"],
        ["めどぅ", "Medusa"],
        ["フラム＝グラス", "TwinElements"],
        ["フラムグラス", "TwinElements"],
        ["フラム", "TwinElements"],
        ["フラマ", "TwinElements"],
        ["フラグラ", "TwinElements"],
        ["双子", "TwinElements"],
        ["アポロン", "Apollo"],
        ["アポロロ", "Apollo"],
        ["アポロ", "Apollo"],
        ["Dエンジェル・オリヴィエ", "DAOlivia"],
        ["オリヴィエ", "DAOlivia"],
        ["Dエンジェル", "DAOlivia"],
        ["Ｄエンジェル", "DAOlivia"],
        ["織部", "(DAOlivia)"],

        ["新石", "T2"],
        ["アテナ", "Athena"],
        ["宛名", "Athena"],
        ["バアル", "Baal"],
        ["巴爾", "Baal"],
        ["グラニ", "Grani"],
        ["ガルーダ", "Garuda"],
        ["ガルダ", "Garuda"],
        ["オーディン", "Odin"],
        ["オディン", "Odin"],
        ["オデン", "Odin"],
        ["おでん", "Odin"],
        ["リッチ", "Lich"],
        ["りっち", "Lich"],

        ["プロメテウス", "Prometheus"],
        ["プロメテ", "Prometheus"],
        ["カー・オン", "Ca Ong"],
        ["カー･オン", "Ca Ong"],
        ["カーオン", "Ca Ong"],
        ["鯨", "Ca Ong"],
        ["バイヴカハ", "Morrigna"],
        ["バイヴガハ", "Morrigna"],
        ["バイブ", "Morrigna"],
        ["バイヴ", "Morrigna"],
        ["ばいがうは", "Morrigna"],
        ["ばいが", "Morrigna"],
        ["ギルガメッシュ", "Gilgamesh"],
        ["ギルガメ", "Gilgamesh"],
        ["ヘクトル", "Hector"],
        ["アヌビス", "Anubis"],

        ["天司", "Primarch"],
        ["ミカエル", "Michael"],
        ["ミカ", "Michael"],
        ["ガブリエル", "Gabriel"],
        ["カブリエル", "Gabriel"],
        ["ガブ", "Gabriel"],
        ["ウリエル", "Uriel"],
        ["ウリ", "Uriel"],
        ["ラファエル", "Raphael"],
        ["ラファ", "Raphael"],
        ["HRT", "Raphael"],
        ["ＨＲＴ", "Raphael"],

        ["シヴァ", "Shiva"],
        ["エウロペ", "Europa"],
        ["エウロパ", "Europa"],
        ["ロペ", "Europa"],
        ["ロパ", "Europa"],
        ["ゴッドガード・ブローディア", "Alexiel"],
        ["ゴッドガード", "Alexiel"],
        ["ブローディア", "Alexiel"],
        ["ゴッブロ", "Alexiel"],
        ["ゴブロ", "Alexiel"],
        ["ゴプロ", "Alexiel"],
        ["ブロ", "Alexiel"],
        ["ｺﾞｯﾌﾞﾛ ", "Alexiel"],
        ["ｺﾞﾌﾞﾛ ", "Alexiel"],
        ["ﾌﾞﾛ ", "Alexiel"],
        ["荒狂う暴風", "Grimnir"],
        ["グリームニル", "Grimnir"],
        ["グリーム", "Grimnir"],
        ["グリー", "Grimnir"],
        ["グリム", "Grimnir"],
        ["メタトロン", "Metatron"],
        ["メタロン", "Metatron"],
        ["メタ", "Metatron"],
        ["アヴァター", "Avatar"],
        ["アバター", "Avatar"],
        ["アバタ", "Avatar"],
        ["アバダー", "Avatar"],
        ["ｱﾊﾞﾀｰ", "Avatar"],
        ["あばた", "Avatar"],

        ["アーカーシャ", "Akasha"],
        ["アーカーチャ", "Akasha"],
        ["アーカシャ", "Akasha"],
        ["アーカーシ", "Akasha"],
        ["アーカー", "Akasha"],
        ["アカーシャ", "Akasha"],
        ["アカシャ", "Akasha"],
        ["アカ", "Akasha"],
        ["ｱｰｶｰｼｬ", "Akasha"],
        ["ｱｰｶｼｬ", "Akasha"],
        ["ｱｰｶｰｼ", "Akasha"],
        ["ｱｶｰｼｬ", "Akasha"],
        ["ｱｶｼｬ", "Akasha"],
        ["ｱｶ", "Akasha"],
        ["あーかーしゃ", "Akasha"],
        ["あかしゃ", "Akasha"],
        ["明石家", "Akasha"],
        ["明石", "Akasha"],
        ["崩天、虚空の兆", "Akasha"],
        ["崩天", "Akasha"],
        ["赤者", "Akasha"],
        ["垢", "Akasha"],
        ["あかちゃん", "Akasha"],
        ["あか", "Akasha"],
        ["マリス", "Malice"],
        ["マリ", "Malice"],
        ["まりす", "Malice"],
        ["まり", "Malice"],
        ["黑风", "Tiaalice"],
	    ["黑風", "TiaMalice"],

        ["幽光の羽", "Gleaming Feather"],
        ["泡影の風羽", "Mystical Feather"],
        ["雄風の葉", "Vortical Pinwheel"],
        ["幽光の砂", "Gleaming Sand Bottle"],
        ["泡影の火砂", "Mystical Flame"],
        ["烈火の岩石", "Searing Stone"],
        ["幽光の水", "Gleaming Water Jug"],
        ["泡影の水流", "Mystical Splash"],
        ["麗水の珊瑚", "Resplendent Coral"],
        ["幽光の岩", "Gleaming Stone"],
        ["泡影の岩砂", "Mystical Alluvium"],
        ["豊沃の琥珀", "Opulent Amber"],
        ["赤銅の古紋", "Bronze Disk"], // "-plated" excluded for conciseness
        ["白銀の古紋", "Silver Disk"],
        ["黄金の古紋", "Gold Disk"],

        ["黒麒麟", "Qilin"],
        ["黑麒麟", "Qilin"],
        ["麒麟", "Qilin"],
        ["黒", "Qilin"],
        ["黑", "Qilin"],
        ["黄龍", "Huanglong"],
        ["龍", "Huanglong"],
        ["黄色", "Yellow"],
        ["黄", "Yellow"],
        ["黄黒", "HuanglongQilin"],
        ["黄黑", "HuanglongQilin"],

        ["火", "Fire"],
        ["水", "Water"],
        ["土", "Earth"],
        ["風", "Wind"],
        ["风", "Wind"],
        ["光", "Light"],
        ["闇", "Dark"],
        ["暗", "Dark"],

        ["雑談", "Chat"],
        ["チャット", "Chat"],
        ["部屋", "Room"],
        ["新規", "New"],
        ["新設", "New"],
        ["新", "New"],
        ["團員募集", "Recruiting"],
        ["団員募集", "Recruiting"],
        ["勧誘", "Recruiting"],
        ["團員以外", "Except Crewmates"],
        ["団員以外", "Except Crewmates"],
        ["團員外", "Except Crewmates"],
        ["団員外", "Except Crewmates"],
        ["團員", "Crewmates"],
        ["団員", "Crewmates"],
        ["団長", "Danchou"],
        ["騎空団", "Crew"],
        ["團", "Crew"],
        ["団", "Crew"],
        ["練習中", "Practice"],
        ["練習", "Practice"],
        ["ソロ", "Quest"],
        ["帯", "Tier"],
        ["ノルマ", "Quota"],
        ["狙い", "Aiming"],
        ["勝ちたい", "Win"],
        ["勝", "Win"],
        ["等", "Etc"],
        ["ログ", "Log"],
        ["スタンプ", "Stamp"],
        ["予選", "Prelim"],
        ["予定", "Planned"],
        ["フリーラン", "Casual"],
        ["位", "Place"],
        ["以内", "Within"],
        ["面接", "Interview"],
        ["妥協", "Compromise"],

        ["出入り自由", "Join/Leave Anytime"],
        ["出入自由", "Join/Leave Anytime"],


        ["ご協力よろしくお願いします", "HelpNeeded"],
        ["ご助力お願い致します", "HelpNeeded"],
        ["助けてください", "HelpNeeded"],
        ["助けてくださ", "HelpNeeded"],
        ["助けてくだ", "HelpNeeded"],
        ["助けてく", "HelpNeeded"],
        ["助けて下さい", "HelpNeeded"],
        ["助けて", "HelpNeeded"],
        ["お助け", "Help"],
        ["ヘルプ", "Help"],
        ["お手伝いお願いします", "HelpNeeded"],
        ["手伝ってください", "HelpNeeded"],
        ["手伝って", "Help"],
	    ["お手伝い", "Help"],
        ["ください", "Please"],
        ["ご協力", "Coordination"],
        ["よろしくおねがいいたします", " "],
        ["よろしくお願いします", " "],
        ["お願いします", " "],
        ["お願い致します", " "],
        ["おねがいします", " "],
        ["願います", " "],
        ["やります", " "],
        ["サクッといきましょう", " "],
        ["長い間待っている", "Waiting"],
        ["のんびり待ちます", "Waiting"],
        ["気ままに待ちます", "Waiting"],
        ["気ままに待ちま", "Waiting"],
        ["気長に待ちますん", "Waiting"],
        ["気長に待ちます", "Waiting"],
        ["気長に待ちま", "Waiting"],
        ["気長い待つ", "Waiting"],
        ["気長い待ち", "Waiting"],
        ["気長い待て", "Waiting"],
        ["気長に", "Waiting"],
        ["待っている", "Waiting"],
        ["待ちます", "Waiting"],
        ["待てる方", "Waiting"],
        ["待つ", "Waiting"],
        ["待ち", "Waiting"],
        ["待て", "Waiting"],
        ["ゆっくり待ちます", "Waiting"],
        ["ゆっくり待ちま", "Waiting"],
        ["ゆっくり待つ", "Waiting"],
        ["ゆっくり待ち", "Waiting"],
        ["ゆっくり待て", "Waiting"],
        ["歓迎", "Welcome"],
        ["あと", "After"],
        ["後", "After"],
        ["と", "And"],
        ["長い間", "LongTime"],
        ["長い", "Long"],
        ["時間", "Time"],
        ["も頑張る", "WorkHard"],
        ["頑張る", "WorkHard"],
        ["頑張", "WorkHard"],
        ["足りてない", "NotEnough"],
        ["参照", "Inquiry"],
        ["または", "Or"],
        ["許可", "Allowed"],
        ["不可", "NotAllowed"],
        ["完全", "Complete"],
        ["完備", "Loaded"],
        ["スクショ", "Screenshot"],
        ["弟子", "Disciple"],
        ["一緒", "Together"],
        ["走りましょ", "Race"],

        ["jk", "JK"],
        ["ＪＫ", "JK"],
        ["ｊｋ", "JK"],
        ["ＨＬ", "HL"],
        ["ｈｌ", "HL"],
        ["ヘル", "HL"],
        ["Ｈ", "Hard"],
        ["ｈ", "Hard"],
        ["Ｎ", "Normal"],
        ["ｎ", "Normal"],
        ["Ｍ", "MVP"],

        ["三十", "30"],
        ["二十", "20"],
        ["十五", "15"],
        ["三", "3"],
        ["二", "2"],
        ["万", "0000"],
        ["千", "000"],
        ["百", "00"],
        ["十八", "18"],
        ["十", "10"],
        ["六", "6"],
        ["五", "5"],
        ["一", "1"],
        ["億", "HundredMil"],

        ["９", "9"],
        ["８", "8"],
        ["７", "7"],
        ["６", "6"],
        ["５", "5"],
        ["３", "3"],
        ["２", "2"],
        ["１", "1"],
        ["０", "0"],
        ["！", "!"],
        ["、", ","],
        ["，", ","],
        ["【", "["],
        ["】", "]"],
        ["～", "~"],
        ["。", "."],
        ["・", ""],
        ["＞", ">"],
        ["＜", "<"],
        ["「", "'"],
        ["」", "'"],
        ["（", "'"],
        ["）", "'"],
        ["％", "%"],

        // Stuff that needed to be put down here or things go weird
        ["石", "Summon"],
        ["デス", "Death"],
        ["ス", "Spartan"],
        ["身内", "Friends"],
        ["无", "No"],
        ["アル", "Ult-"],
        ["名", "players"],
        ["素材", "Mats"],
        ["プロ", "Proto-"],
        ["高", "High"],
        ["ト", "Thor"],
        ["卜", "Thor"],
        ["ﾄ", "Thor"],
        ["外出", "Pub"],
        ["外部", "Pub"],
        ["外", "Pub"],
        ["は", " "],
        ["です", " "],
        ["の", " "],
        ["者", "Player"],
        ["よわ", "Weak"], //Meaning weak, proto-baha is also called weak baha
        ["バ", "Baha"],
        ["不在", "NotHere"],
        ["个", "↑"],
        ["当社比", "ComparedToOthers"],

    ];

    var translationMap = {};
    var translationRegexp = [];
    for (let [from, to] of translations) {
        translationMap[from] = to;
        translationRegexp.push(from);
    }
    // NOTE: this assumes `from` contains no special regex characters
    translationRegexp = new RegExp("(" + translationRegexp.join("|") + ")", "g");

    function translateComment(c) {
        let repPrefix = "" + Math.random();
        let replaced = [];
        let matches = c.match(translationRegexp);
        if (!matches) {
            return c;
        }
        for (let from of matches) {
            let to = translationMap[from];
            // NOTE: `to` and `from` are used, unescaped, as HTML
            if (c.indexOf(from) !== -1) {
                let i = replaced.length;
                replaced.push([from, to]);
                c = c.replace(from, repPrefix + i);
            }
        }
        for (let i = 0, n = replaced.length; i < n; ++i) {
            let [from, to] = replaced[i];
            c = c.replace(repPrefix + i, "<span style='color:#1f5121'>" + to + "</span>");
        }
        return c;
    }

    function translateComments() {
        let comments = document.getElementsByClassName("txt-room-comment");
        for (let comment of comments) {
            let orig = comment.innerHTML;
            let translated = translateComment(orig);
            if (translated !== orig) {
                comment.addEventListener("contextmenu", function(ev) {
                    prompt("Original Description:", orig);
                    ev.preventDefault();
                });
                comment.innerHTML = translated;
                comment.title = orig;
            }
        }
    }

    function toString() {
        return "".toString.toString();
    }
    toString.toString = toString;

    function hookArguments(o, name, f) {
        let p = o.prototype;
        let orig = p[name];
        p[name] = function() {
            f.apply(this, arguments);
            return orig.apply(this, arguments);
        };
        p[name].toString = function() {
            return orig.toString();
        };
        p[name].toString.toString = toString;
    }

    function installHooks() {
        hookArguments(XMLHttpRequest, "send", function() {
            this.addEventListener("readystatechange", function() {
                if (this.readyState != XMLHttpRequest.DONE) { return; }
                let contentType = this.getResponseHeader("Content-Type") || "";
                if (this.status == 200 &&
                    contentType.indexOf("application/json") !== -1) {
                    if (this.responseURL.indexOf("/coopraid/offers/") !== -1 ||
                        this.responseURL.indexOf("/lobby/offers/") !== -1 ||
                        this.responseURL.indexOf("/coopraid/content/room/") !== -1) {
                        // The comment views will be rendered later in this
                        // tick, so defer translation to the next tick.
                        setTimeout(translateComments, 0);
                    }
                }
            }, false);
        });
    }

    installHooks();
})();
